import * as admin from 'firebase-admin';
import * as fs from 'fs';
import * as path from 'path';

// Force to use emulator
process.env.FIRESTORE_EMULATOR_HOST = process.env.FIRESTORE_EMULATOR_HOST || '127.0.0.1:8080';
process.env.FIREBASE_AUTH_EMULATOR_HOST = process.env.FIREBASE_AUTH_EMULATOR_HOST || '127.0.0.1:9099';
process.env.GCLOUD_PROJECT = 'demo-uat-project';
process.env.FIREBASE_PROJECT_ID = 'demo-uat-project';

// Initialize admin app if not already initialized
if (!admin.apps.length) {
    admin.initializeApp({
        projectId: 'demo-uat-project'
    });
}
const db = admin.firestore();
const auth = admin.auth();

const SEED_DATA = {
    user: {
        uid: 'uat-user-1',
        email: 'uat.user@test.com',
        displayName: 'UAT User',
        password: 'password123'
    },
    project: {
        id: 'uat-project-1',
        title: 'The Automated Epic',
        synopsis: 'A story generated by a machine for testing purposes.',
        wordCount: 0,
        createdAt: admin.firestore.Timestamp.now(),
        updatedAt: admin.firestore.Timestamp.now()
    },
    chapter: {
        id: 'uat-chapter-1',
        title: 'Chapter 1: The Boot Up',
        content: '<p>The machine came to life.</p>',
        order: 0,
        wordCount: 5,
        createdAt: admin.firestore.Timestamp.now(),
        updatedAt: admin.firestore.Timestamp.now()
    },
    entity: {
        id: 'uat-entity-1',
        name: 'The UAT AI',
        type: 'character',
        description: 'A strict judge and creator.',
        tags: ['protagonist', 'ai'],
        createdAt: admin.firestore.Timestamp.now(),
        updatedAt: admin.firestore.Timestamp.now()
    }
};

async function seed() {
    console.log('🌱 Starting UAT Seed Process...');

    // 1. Create or Overwrite User Auth
    try {
        await auth.deleteUser(SEED_DATA.user.uid);
    } catch (e: any) {
        if (e.code !== 'auth/user-not-found') {
            console.warn(`User deletion warning: ${e.message}`);
        }
    }

    await auth.createUser({
        uid: SEED_DATA.user.uid,
        email: SEED_DATA.user.email,
        password: SEED_DATA.user.password,
        displayName: SEED_DATA.user.displayName,
    });
    console.log(`✅ Auth user created: ${SEED_DATA.user.uid}`);

    // 2. Seed Database
    const batch = db.batch();

    // User doc
    batch.set(db.collection('users').doc(SEED_DATA.user.uid), {
        email: SEED_DATA.user.email,
        displayName: SEED_DATA.user.displayName,
        createdAt: admin.firestore.FieldValue.serverTimestamp()
    });

    // Project doc
    batch.set(db.collection('projects').doc(SEED_DATA.project.id), {
        ...SEED_DATA.project,
        userId: SEED_DATA.user.uid, // Owner
    });

    // Chapter doc
    batch.set(
        db.collection('projects').doc(SEED_DATA.project.id)
            .collection('chapters').doc(SEED_DATA.chapter.id),
        SEED_DATA.chapter
    );

    // Entity doc
    batch.set(
        db.collection('projects').doc(SEED_DATA.project.id)
            .collection('entities').doc(SEED_DATA.entity.id),
        SEED_DATA.entity
    );

    await batch.commit();
    console.log(`✅ Firestore seeded with project: ${SEED_DATA.project.id}`);

    // 3. Generate Custom Token
    const customToken = await auth.createCustomToken(SEED_DATA.user.uid);

    // 4. Write output mapping to `.seed.json`
    const outputMap = {
        userId: SEED_DATA.user.uid,
        userEmail: SEED_DATA.user.email,
        userPassword: SEED_DATA.user.password,
        customToken: customToken,
        projectId: SEED_DATA.project.id,
        chapterId: SEED_DATA.chapter.id,
        entityId: SEED_DATA.entity.id,
        seededAt: new Date().toISOString()
    };

    const seedFilePath = path.join(__dirname, '..', '.seed.json');
    fs.writeFileSync(seedFilePath, JSON.stringify(outputMap, null, 2));

    console.log(`✅ Seed mapping written to: ${seedFilePath}`);
    console.log('🌱 UAT Seed Process Complete!');
}

seed()
    .then(() => process.exit(0))
    .catch(e => {
        console.error('❌ Seeding failed:', e);
        process.exit(1);
    });
